### ISSUE TITLE
program does not load. after i select my account it shows a window that says 'welcome to the future' and stops. i'm using the latest version. 

### ISSUE THREAD

**Issue by szeero59** [timiimit/UT4UU-Public#17]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**System Information (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Build Configuration: [Game, Server or Editor]
 - Version [e.g. v10.0b5; find with `uu info`]

**Additional context**

**Comment by ArchibaldT1** [comment]
This workaround may help meanwhile if UT4UU 10.1.2 hangs at startup with "the future" screen (Win10):
- install https://ut4.timiimit.com/Instructions/StockUT4
- restart UT
- setup https://ut4.timiimit.com/Instructions/UT4UU
- remove StockUT4 config

**Comment by szeero59** [comment]
Thanks, it's working well now.

**Comment by szeero59** [comment]
I'm having problems logging into the master server. Says p/w is invalid.
How do I rest my p/w? Thanks.

**Comment by timiimit** [comment]
This issue has been resolved as you already said. If you have more problems with UT4UU please open a new issue.

You say you are unable to login to new master server. That is not in the scope of UT4UU. I can reset your password if you send me the email address and username you registered with on Discord. Do not send your information here because this is a public conversation and I will be unable to send you the new password.

Locking conversation here.
